# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LXDevkitNetworkLayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'
  
  # Pods for LXDevkitNetworkLayer

  target 'LXDevkitNetworkLayerTests' do
    # Pods for testing
  end

end

target 'LXDevkitNetworkLayerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for LXDevkitNetworkLayerExample

end
